name = "wakeonlan-web"
main = "worker.js"
compatibility_date = "2026-07-09"
workers_dev = true

[[kv_namespaces]]
binding = "WOL_STATE"
id = "6c19831b829f4044a8e2b7d51605ab39"

[vars]
PC_NAME = "Home PC"
RELAY_OFFLINE_AFTER_SECONDS = "20"
RELAY_POLL_SECONDS = "3"
CLAIM_TIMEOUT_SECONDS = "30"
